const checkbox = document.getElementById('checkbox');
const body = document.getElementById('body')
const h1 = document.getElementById('h1')
const label = document.getElementById('label')
const cont1 = document.getElementById('cont1')
const h4 = document.getElementById('h4')
const item= document.getElementById('item')
const item2 = document.getElementById('item2')
const item1= document.getElementById('item1')
const item3= document.getElementById('item3')
const items1= document.getElementById('items1')
const items2= document.getElementById('items2')
const items3= document.getElementById('items3')
const items4= document.getElementById('items4')
const items5= document.getElementById('items5')
const items6= document.getElementById('items6')
const items7= document.getElementById('items7')
const items8= document.getElementById('items8')
const h12= document.getElementById('h12')
const h13= document.getElementById('h13')
const h14= document.getElementById('h14')
const h15= document.getElementById('h15')
const h16= document.getElementById('h16')
const h17= document.getElementById('h17')
const h18= document.getElementById('h18')
const h19= document.getElementById('h19')
const h2= document.getElementById('h2')
const h3= document.getElementById('h3')
const h5= document.getElementById('h5')
const h6= document.getElementById('h6')


label.addEventListener("switch", light);

function light() {
    body.classList.toggle('light')
    h1.classList.toggle('light')
    cont1.classList.toggle('light')
    h4.classList.toggle('light')
    item.classList.toggle('light')
    item2.classList.toggle('light')
    item1.classList.toggle('light')
    item3.classList.toggle('light')
    items1.classList.toggle('light')
    items2.classList.toggle('light')
    items3.classList.toggle('light')
    items4.classList.toggle('light')
    items5.classList.toggle('light')
    items6.classList.toggle('light')
    items7.classList.toggle('light')
    items8.classList.toggle('light')
    h12.classList.toggle('light')
    h13.classList.toggle('light')
    h14.classList.toggle('light')
    h15.classList.toggle('light')
    h16.classList.toggle('light')
    h17.classList.toggle('light')
    h18.classList.toggle('light')
    h19.classList.toggle('light')
    h2.classList.toggle('light')
    h3.classList.toggle('light')
    h5.classList.toggle('light')
    h6.classList.toggle('light')
}



//   () => {  document.body.classList.toggle('light')
// });
